Repository fossasia/phimpme-android, pull requests merged in 2019-11, with the labels that each got.

#2902 fix: Margin of snackbar in single media activity
  app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java
  app/src/main/res/layout/activity_pager.xml
Labels: fix

#2901 fix: crash on orientation change while crop
  app/src/main/java/org/fossasia/phimpme/editor/fragment/CropFragment.java
Labels: fix

#2905 chore(deps): Bump gradle from 3.5.0 to 3.5.2
  build.gradle
Labels: dependencies

#2911 fix: removed stetho dependency
  app/build.gradle
  app/src/main/java/org/fossasia/phimpme/MyApplication.java
Labels: fix

#2913 chore: Version name changed to 1.10.0
  app/build.gradle
Labels: chore

#2917 chore: Update aab path in release script
  scripts/update-apk.sh
Labels: chore

#2934 fix: removed materialshowcase libary due to crash on android 10
  app/build.gradle
  app/src/main/java/org/fossasia/phimpme/base/BaseActivity.java
  app/src/main/java/org/fossasia/phimpme/opencamera/Preview/Preview.java
  app/src/main/res/values/strings.xml
Labels: fix
