Repository fossasia/phimpme-android, pull requests merged in 2019-09, with the labels that each got.

#2862 chore(docs): Corrected the path of staticlibs folder
  README.md
Labels: chore, docs

#2864 fix: Permission flow in splash screen
  app/src/main/java/org/fossasia/phimpme/gallery/activities/SplashScreen.java
Labels: fix

#2869 chore: updated buildtools, targetsdk, compilesdk version to 29
  app/build.gradle
Labels: chore

#2870 fix: crash on connect to us on facebook in about section
  app/src/main/java/org/fossasia/phimpme/gallery/activities/AboutActivity.java
Labels: fix

#2874 fix: Text in edit image screen disappears on rotation
  app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java
Labels: fix

#2880 chore(deps): nextcloud sdk to 1.5.0
  app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java
  build.gradle
Labels: dependencies
